// product
export const FETCH_ORDER_GUIDE_PRODUCTS = 'FETCH_ORDER_GUIDE_PRODUCTS'
export const FETCH_ORDER_GUIDE_PRODUCTS_SUCCESS = 'FETCH_ORDER_GUIDE_PRODUCTS_SUCCESS'
export const FETCH_ORDER_GUIDE_PRODUCTS_FAIL = 'FETCH_ORDER_GUIDE_PRODUCTS_FAIL'

// edit order guide
export const SAVE_ORDER_GUIDE = 'SAVE_ORDER_GUIDE'
export const SAVE_ORDER_GUIDE_SUCCESS = 'SAVE_ORDER_GUIDE_SUCCESS'
export const TOGGLE_EDIT_MODAL = 'TOGGLE_EDIT_MODAL'
export const CLOSE_SUCCESS_BANNER = 'CLOSE_SUCCESS_BANNER'

// place order
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS'
export const UPDATE_PLACE_ORDER_QUANTITY = 'UPDATE_PLACE_ORDER_QUANTITY'
export const CLEAR_PLACE_ORDER = 'CLEAR_PLACE_ORDER'
export const DELETE_PLACE_ORDER_PRODUCT = 'DELETE_PLACE_ORDER_PRODUCT'
export const CLOSE_ORDER_SUCCESS_BANNER = 'CLOSE_ORDER_SUCCESS_BANNER'