// product
export const FETCH_ORDER_GUIDE_PRODUCTS = 'FETCH_ORDER_GUIDE_PRODUCTS'
export const FETCH_ORDER_GUIDE_PRODUCTS_SUCCESS = 'FETCH_ORDER_GUIDE_PRODUCTS_SUCCESS'
export const FETCH_ORDER_GUIDE_PRODUCTS_FAIL = 'FETCH_ORDER_GUIDE_PRODUCTS_FAIL'

// edit order guide
export const SAVE_ORDER_GUIDE = 'SAVE_ORDER_GUIDE'
export const SAVE_ORDER_GUIDE_SUCCESS = 'SAVE_ORDER_GUIDE_SUCCESS'
export const TOGGLE_EDIT_MODAL = 'TOGGLE_EDIT_MODAL'
export const CLOSE_SUCCESS_BANNER = 'CLOSE_SUCCESS_BANNER'

// place order
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS'